routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/products/{id}/detail', 'ProductDetailController@show')->name('detail');

Route::middleware(['auth'])->group(function () {
    Route::post('product/{product}/orders', 'OrderController@store')->name('orders.store');
    Route::resource('orders', 'OrderController')->only(['index', 'destroy']);
});

Route::middleware(['auth', 'role:admin'])->group(function () {
    Route::get('users', 'UserController@index')->name('users.index');
    Route::resource('companies', 'CompanyController');
    Route::resource('stores', 'StoreController');
    Route::resource('products', 'ProductController');
    Route::resource('campaigns', 'CampaignController');
});

app/Models/Campaign.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * @property int|null total_product_limit
 * @property int|null product_limit_per_user
 * @property int id
 */
class Campaign extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'total_product_limit',
        'product_limit_per_user',
        'start_at',
        'end_at',
    ];

    /**
     * The stores that belong to the campaign.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function stores()
    {
        return $this->belongsToMany(Store::class);
    }

    /**
     * The products that belong to the campaign.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function products()
    {
        return $this->belongsToMany(Product::class);
    }

    /**
     * Get the orders for the campaign.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function orders()
    {
        return $this->hasMany(Order::class);
    }

    /**
     * @return int
     */
    public function totalOrderedProductCount(): int
    {
        return (int) $this->orders()->sum('amount');
    }
}

app/Http/Controllers/CampaignController.php
<?php

namespace App\Http\Controllers;

use App\Models\Campaign;
use Illuminate\Http\Request;
use Illuminate\Database\Eloquent\Builder;
use App\Http\Requests\Campaign\StoreCampaignRequest;
use App\Http\Requests\Campaign\UpdateCampaignRequest;

class CampaignController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $campaignQuery = Campaign::query();

        $productId = $request->input('product_id');
        $campaignQuery->when($productId, function (Builder $q) use ($productId) {
            $q->whereHas('products', function (Builder $q) use ($productId) {
                $q->where('id', $productId);
            });
        });

        $campaigns = $campaignQuery->paginate();

        return view('campaign.index', compact('campaigns'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('campaign.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \App\Http\Requests\Campaign\StoreCampaignRequest $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(StoreCampaignRequest $request)
    {
        $campaignAttributes = [
            'name'                       => $request->input('name'),
            'total_product_limit'        => $request->input('total_product_limit'),
            'product_limit_per_user'     => $request->input('product_limit_per_user'),
            'start_at'                   => $request->input('start_at'),
            'end_at'                     => $request->input('end_at'),
        ];

        Campaign::query()->create($campaignAttributes);

        return redirect()->route('campaigns.index')->with('success', 'The campaign has successfully saved.');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function show(int $id)
    {
        $campaign = Campaign::query()->findOrFail($id);

        return view('campaign.show', compact('campaign'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit(int $id)
    {
        $campaign = Campaign::query()->findOrFail($id);

        return view('campaign.edit', compact('campaign'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \App\Http\Requests\Campaign\UpdateCampaignRequest $request
     * @param int                                               $id
     *
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateCampaignRequest $request, int $id)
    {
        $campaign = Campaign::query()->findOrFail($id);

        $campaignAttributes = [
            'name'                       => $request->input('name'),
            'total_product_limit'        => $request->input('total_product_limit'),
            'product_limit_per_user'     => $request->input('product_limit_per_user'),
            'start_at'                   => $request->input('start_at'),
            'end_at'                     => $request->input('end_at'),
        ];

        $campaign->update($campaignAttributes);

        return redirect()->route('campaigns.index')->with('success', 'The campaign has successfully updated.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy(int $id)
    {
        $campaign = Campaign::query()->findOrFail($id);

        $campaign->delete();

        return redirect()->route('campaigns.index')->with('success', "The campaign [{$campaign->name}] has successfully deleted.");
    }
}

resources/views/campaign/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">

                <form method="POST" action="{{ route('campaigns.store') }}">
                    @csrf
                    <div class="form-group">
                        <label for="nameInput">Name</label>
                        <input type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" id="nameInput" placeholder="Enter Name">
                        @error('name')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label for="totalProductLimit">Total Product Limit</label>
                        <input type="number" pattern="\d*"  class="form-control @error('total_product_limit') is-invalid @enderror" value="{{ old('total_product_limit') }}" name="total_product_limit" id="totalProductLimit" placeholder="Enter Total Product Limit">
                        @error('total_product_limit')
                        <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label for="productLimitPerUser">Product Limit Per User</label>
                        <input type="number" pattern="\d*" class="form-control @error('product_limit_per_user') is-invalid @enderror" value="{{ old('product_limit_per_user') }}" name="product_limit_per_user" id="productLimitPerUser" placeholder="Enter Product Limit Per User">
                        @error('product_limit_per_user')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label for="startAt">Start At</label>
                        <input type="text" class="form-control @error('start_at') is-invalid @enderror" value="{{ old('start_at') }}" name="start_at" id="startAt" placeholder="Enter Start Date, Ex: 2018-11-20">
                        @error('start_at')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label for="endAt">End At</label>
                        <input type="text" class="form-control @error('end_at') is-invalid @enderror" value="{{ old('end_at') }}" name="end_at" id="endAt" placeholder="Enter End Date, Ex: 2018-11-27">
                        @error('end_at')
                        <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>

                    <button type="submit" class="btn btn-primary">Create</button>
                </form>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    @parent
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script type="text/javascript" src="{{ asset('js/jquery.mask.min.js') }}"></script>
    <script type="text/javascript">
        $(document).ready(function($){
            $('#startAt').mask('0000-00-00');
            $('#endAt').mask('0000-00-00');
        });
    </script>
@endsection

resources/views/campaign/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">

                <form method="POST" action="{{ route('campaigns.update', ['id' => $campaign->id]) }}">
                    @method('PUT')
                    @csrf
                    <div class="form-group">
                        <label for="nameInput">Name</label>
                        <input type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ $campaign->name }}" id="nameInput" placeholder="Enter Name">
                        @error('name')
                        <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label for="totalProductLimit">Total Product Limit</label>
                        <input type="number" pattern="\d*" class="form-control @error('total_product_limit') is-invalid @enderror" value="{{ $campaign->total_product_limit }}" name="total_product_limit" id="totalProductLimit" placeholder="Enter Total Product Limit">
                        @error('total_product_limit')
                        <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label for="productLimitPerUser">Product Limit Per User</label>
                        <input type="number" pattern="\d*" class="form-control @error('product_limit_per_user') is-invalid @enderror" value="{{ $campaign->product_limit_per_user }}" name="product_limit_per_user" id="productLimitPerUser" placeholder="Enter Product Limit Per User">
                        @error('product_limit_per_user')
                        <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label for="startAt">Start At</label>
                        <input type="text" class="form-control @error('start_at') is-invalid @enderror" value="{{ $campaign->start_at }}" name="start_at" id="startAt" placeholder="Enter Start Date, Ex: 2018-11-20">
                        @error('start_at')
                        <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label for="endAt">End At</label>
                        <input type="text" class="form-control @error('end_at') is-invalid @enderror" value="{{ $campaign->end_at }}" name="end_at" id="endAt" placeholder="Enter End Date, Ex: 2018-11-27">
                        @error('end_at')
                        <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>

                    <button type="submit" class="btn btn-primary">Update</button>
                </form>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    @parent
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script type="text/javascript" src="{{ asset('js/jquery.mask.min.js') }}"></script>
    <script type="text/javascript">
        $(document).ready(function($){
            $('#startAt').mask('0000-00-00');
            $('#endAt').mask('0000-00-00');
        });
    </script>
@endsection

resources/views/campaign/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">

                <a href="{{ route('campaigns.create') }}" class="btn btn-primary float-right mb-3" role="button">Create Campaign</a>

                <table class="table">
                    <thead class="thead-light">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Name</th>
                        <th scope="col">Start At</th>
                        <th scope="col">End At</th>
                        <th scope="col">Created At</th>
                        <th scope="col">Updated At</th>
                        <th scope="col" class="text-center">Operation</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($campaigns as $campaign)
                        <tr>
                            <th class="align-middle" scope="row">{{ $campaign->id }}</th>
                            <td class="align-middle">{{ $campaign->name }}</td>
                            <td class="align-middle">{{ $campaign->start_at }}</td>
                            <td class="align-middle">{{ $campaign->end_at }}</td>
                            <td class="align-middle">{{ $campaign->created_at }}</td>
                            <td class="align-middle">{{ $campaign->updated_at }}</td>
                            <td class="align-middle text-center">
                                <a href="{{ route('campaigns.edit', ['id' => $campaign->id ]) }}" class="btn btn-success" role="button">Edit</a>

                                <form action="{{route('campaigns.destroy',[$campaign->id])}}" method="POST" style="display: inline;">
                                    @method('DELETE')
                                    @csrf
                                    <button type="submit" class="btn btn-danger">Delete</button>
                                </form>

                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>

                {{ $campaigns->links() }}
            </div>
        </div>
    </div>
@endsection