routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/products/{id}/detail', 'ProductDetailController@show')->name('detail');

Route::middleware(['auth'])->group(function () {
    Route::post('product/{product}/orders', 'OrderController@store')->name('orders.store');
    Route::resource('orders', 'OrderController')->only(['index', 'destroy']);
});

Route::middleware(['auth', 'role:admin'])->group(function () {
    Route::get('users', 'UserController@index')->name('users.index');
    Route::resource('companies', 'CompanyController');
    Route::resource('stores', 'StoreController');
    Route::resource('products', 'ProductController');
    Route::resource('campaigns', 'CampaignController');
});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * @property int id
 */
class Product extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'campaign_id',
    ];

    /**
     * The campaigns that belong to the product.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function campaigns()
    {
        return $this->belongsToMany(Campaign::class);
    }

    /**
     * The stores that belong to the product.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function stores()
    {
        return $this->belongsToMany(Store::class);
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Models\Store;
use App\Models\Product;
use App\Models\Campaign;
use Illuminate\Http\Request;
use App\Http\Requests\Product\StoreProductRequest;
use App\Http\Requests\Product\UpdateProductRequest;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::query()->withCount(['campaigns', 'stores'])->paginate();

        return view('product.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // @TODO we can use autocomplete in view.
        $campaigns = Campaign::query()->limit(10)->latest()->get();

        // @TODO we can use autocomplete in view.
        $stores = Store::query()->limit(10)->latest()->get();

        return view('product.create', compact('campaigns', 'stores'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \App\Http\Requests\Product\StoreProductRequest $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(StoreProductRequest $request)
    {
        /** @var Product $product */
        $product = Product::query()->create([
            'name'     => $request->input('name'),
        ]);

        $campaigns = array_filter($request->input('campaigns', []));
        $product->campaigns()->sync($campaigns);

        $stores = $request->input('stores', []);
        $product->stores()->sync($stores);

        return redirect()->route('products.index')->with('success', 'The product has successfully saved.');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function show(int $id)
    {
        $product = Product::query()->with('campaigns', 'stores')->findOrFail($id);

        return view('product.show', compact('product'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit(int $id)
    {
        $product = Product::query()->with('campaigns', 'stores')->findOrFail($id);

        $currentCampaigns = $product->campaigns->pluck('id');

        // @TODO we can use autocomplete in view.
        $campaigns = Campaign::query()->limit(10)->whereNotIn('id', $currentCampaigns)->latest()->get();

        $currentStores = $product->stores->pluck('id');
        // @TODO we can use autocomplete in view.
        $stores = Store::query()->limit(10)->whereNotIn('id', $currentStores)->latest()->get();

        return view('product.edit', compact('product', 'campaigns', 'stores'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \App\Http\Requests\Product\UpdateProductRequest $request
     * @param int                                             $id
     *
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateProductRequest $request, int $id)
    {
        /** @var Product $product */
        $product = Product::query()->findOrFail($id);

        $product->update([
            'name'     => $request->input('name'),
        ]);

        $campaigns = array_filter($request->input('campaigns', []));
        $product->campaigns()->sync($campaigns);

        $stores = $request->input('stores', []);
        $product->stores()->sync($stores);

        return redirect()->route('products.index')->with('success', 'The product has successfully updated.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy(int $id)
    {
        $product = Product::query()->findOrFail($id);

        $product->delete();

        return redirect()->route('products.index')->with('success', "The product [{$product->name}] has successfully deleted.");
    }
}

resources/views/product/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">

                <form method="POST" action="{{ route('products.store') }}">
                    @csrf
                    <div class="form-group">
                        <label for="nameInput">Name</label>
                        <input type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" id="nameInput" placeholder="Enter Name">
                        @error('name')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label for="campaigns">Campaigns</label>
                        <select multiple class="form-control" name="campaigns[]" id="campaigns">
                            <option></option>
                            @foreach($campaigns as $campaign)
                                <option value="{{ $campaign->id }}"> {{ $campaign->name }}</option>
                            @endforeach
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="stores">Stores</label>
                        <select multiple class="form-control" name="stores[]" id="stores">
                            <option></option>
                            @foreach($stores as $store)
                                <option value="{{ $store->id }}"> {{ $store->name }}</option>
                            @endforeach
                        </select>
                    </div>


                    <button type="submit" class="btn btn-primary">Create</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/product/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">

                <form method="POST" action="{{ route('products.update', ['id' => $product->id]) }}">
                    @method('PUT')
                    @csrf
                    <div class="form-group">
                        <label for="nameInput">Name</label>
                        <input type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ $product->name }}" id="nameInput" placeholder="Enter Name">
                        @error('name')
                        <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label for="campaigns">Campaigns</label>
                        <select multiple class="form-control" name="campaigns[]" id="campaigns">
                            <option></option>
                            @foreach($product->campaigns as $productCampaign)
                                <option value="{{ $productCampaign->id }}" selected> {{ $productCampaign->name }}</option>
                            @endforeach
                            @foreach($campaigns as $campaign)
                                <option value="{{ $campaign->id }}"> {{ $campaign->name }}</option>
                            @endforeach
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="stores">Stores</label>
                        <select multiple class="form-control" name="stores[]" id="stores">
                            <option></option>
                            @foreach($product->stores as $productStore)
                                <option value="{{ $productStore->id }}" selected> {{ $productStore->name }}</option>
                            @endforeach
                            @foreach($stores as $store)
                                <option value="{{ $store->id }}"> {{ $store->name }}</option>
                            @endforeach
                        </select>
                    </div>

                    <button type="submit" class="btn btn-primary">Update</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/product/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">

                <a href="{{ route('products.create') }}" class="btn btn-primary float-right mb-3" role="button">Create Product</a>

                <table class="table">
                    <thead class="thead-light">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Name</th>
                        <th scope="col" class="text-center">Campaigns</th>
                        <th scope="col" class="text-center">Stores</th>
                        <th scope="col">Created At</th>
                        <th scope="col">Updated At</th>
                        <th scope="col" class="text-center">Operation</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($products as $product)
                        <tr>
                            <th class="align-middle" scope="row">{{ $product->id }}</th>
                            <td class="align-middle">{{ $product->name }}</td>
                            <td class="align-middle text-center"><a href="{{ route('campaigns.index', ['product_id' => $product->id]) }}">{{ $product->campaigns_count }}</a></td>
                            <td class="align-middle text-center"><a href="{{ route('stores.index', ['product_id' => $product->id]) }}">{{ $product->stores_count }}</a></td>
                            <td class="align-middle">{{ $product->created_at }}</td>
                            <td class="align-middle">{{ $product->updated_at }}</td>
                            <td class="align-middle text-center">
                                <a href="{{ route('products.show', ['id' => $product->id ]) }}" class="btn btn-primary" role="button">Show</a>

                                <a href="{{ route('products.edit', ['id' => $product->id ]) }}" class="btn btn-success" role="button">Edit</a>

                                <form action="{{route('products.destroy',['id' => $product->id])}}" method="POST" style="display: inline;">
                                    @method('DELETE')
                                    @csrf
                                    <button type="submit" class="btn btn-danger">Delete</button>
                                </form>

                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>

                {{ $products->links() }}
            </div>
        </div>
    </div>
@endsection

resources/views/product/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <h5 class="card-header">{{ $product->name }}</h5>
                    <div class="card-body">
                        <p class="card-text">
                        <table>
                            <tr>
                                <th class="text-muted pr-2" scope="row">Name</th>
                                <td></td>
                                <td>{{ $product->name }}</td>
                            </tr>
                            <tr>
                                <th class="text-muted pr-2" scope="row">Created At</th>
                                <td></td>
                                <td>{{ $product->created_at }}</td>
                            </tr>
                            <tr>
                                <th class="text-muted pr-2" scope="row">Updated At</th>
                                <td></td>
                                <td>{{ $product->updated_at }}</td>
                            </tr>
                            <tr>
                                <th class="text-muted pr-2" scope="row">Campaigns</th>
                                <td></td>
                                <td>
                                    @foreach($product->campaigns as $campaign)
                                        <a href="{{ route('campaigns.edit', ['id' => $campaign->id]) }}" title="{{ $campaign->name }}"> {{ $campaign->name }}</a>  @if (!$loop->last) | @endif
                                    @endforeach
                                </td>
                            </tr>
                            <tr>
                                <th class="text-muted pr-2" scope="row">Stores</th>
                                <td></td>
                                <td>
                                    @foreach($product->stores as $store)
                                        <a href="{{ route('stores.edit', ['id' => $store->id]) }}" title="{{ $store->name }}"> {{ $store->name }}</a> @if (!$loop->last) | @endif
                                    @endforeach
                                </td>
                            </tr>
                        </table>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection