routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/products/{id}/detail', 'ProductDetailController@show')->name('detail');

Route::middleware(['auth'])->group(function () {
    Route::post('product/{product}/orders', 'OrderController@store')->name('orders.store');
    Route::resource('orders', 'OrderController')->only(['index', 'destroy']);
});

Route::middleware(['auth', 'role:admin'])->group(function () {
    Route::get('users', 'UserController@index')->name('users.index');
    Route::resource('companies', 'CompanyController');
    Route::resource('stores', 'StoreController');
    Route::resource('products', 'ProductController');
    Route::resource('campaigns', 'CampaignController');
});

app/Models/Store.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Store extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'description',
        'address',
        'company_id',
    ];

    /**
     * Get the company that owns the store.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function company()
    {
        return $this->belongsTo(Company::class);
    }

    /**
     * The campaigns that belong to the store.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function campaigns()
    {
        return $this->belongsToMany(Campaign::class);
    }

    /**
     * The products that belong to the store.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function products()
    {
        return $this->belongsToMany(Product::class);
    }
}

app/Http/Controllers/StoreController.php
<?php

namespace App\Http\Controllers;

use App\Models\Store;
use App\Models\Company;
use Illuminate\Http\Request;
use App\Http\Requests\Store\StoreRequest;
use Illuminate\Database\Eloquent\Builder;
use App\Http\Requests\Store\UpdateStoreRequest;

class StoreController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $storeQuery = Store::query()->with('company');

        $productId = $request->input('product_id');
        $storeQuery->when($productId, function (Builder $q) use ($productId) {
            $q->whereHas('products', function (Builder $q) use ($productId) {
                $q->where('id', $productId);
            });
        });

        $stores = $storeQuery->paginate();

        return view('store.index', compact('stores'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // @TODO we can use autocomplete in view.
        $companies = Company::query()->limit(10)->latest()->get();

        return view('store.create', compact('companies'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \App\Http\Requests\Store\StoreRequest $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(StoreRequest $request)
    {
        Store::query()->create([
            'name'           => $request->input('name'),
            'description'    => $request->input('description'),
            'address'        => $request->input('address'),
            'company_id'     => $request->input('company_id'),
        ]);

        return redirect()->route('stores.index')->with('success', 'The store has successfully saved.');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function show(int $id)
    {
        $store = Store::query()->findOrFail($id);

        return view('store.show', compact('store'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit(int $id)
    {
        $store = Store::query()->findOrFail($id);

        // @TODO we can use autocomplete in view.
        $companies = Company::query()->limit(10)->latest()->get();

        return view('store.edit', compact('store', 'companies'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \App\Http\Requests\Store\UpdateStoreRequest $request
     * @param int                                         $id
     *
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateStoreRequest $request, int $id)
    {
        /** @var Store $store */
        $store = Store::query()->findOrFail($id);

        $store->update([
            'name'           => $request->input('name'),
            'description'    => $request->input('description'),
            'address'        => $request->input('address'),
            'company_id'     => $request->input('company_id'),
        ]);

        return redirect()->route('stores.index')->with('success', 'The store has successfully updated.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy(int $id)
    {
        $store = Store::query()->findOrFail($id);

        $store->delete();

        return redirect()->route('stores.index')->with('success', "The store [{$store->name}] has successfully updated.");
    }
}

resources/views/store/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">

                <form method="POST" action="{{ route('stores.store') }}">
                    @csrf
                    <div class="form-group">
                        <label for="nameInput">Name</label>
                        <input type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" id="nameInput" placeholder="Enter Name">
                        @error('name')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label for="description">Description</label>
                        <textarea class="form-control @error('description') is-invalid @enderror" rows="4" name="description" id="description">{{ old('description') }}</textarea>
                        @error('description')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label for="address">Address</label>
                        <textarea class="form-control @error('address') is-invalid @enderror" rows="2" name="address" id="address">{{ old('address') }}</textarea>
                        @error('address')
                        <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label for="company">Company</label>
                        <select class="form-control @error('company_id') is-invalid @enderror" name="company_id" id="company">
                            <option value="">--Select Company--</option>
                            @foreach($companies as $company)
                                <option value="{{ $company->id }}">{{ $company->name }}</option>
                            @endforeach
                        </select>
                        @error('company_id')
                        <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>

                    <button type="submit" class="btn btn-primary">Create</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/store/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <form method="POST" action="{{ route('stores.update', ['id' => $store->id]) }}">
                    @method('PUT')
                    @csrf
                    <div class="form-group">
                        <label for="nameInput">Name</label>
                        <input type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ $store->name }}" id="nameInput" placeholder="Enter Name">
                        @error('name')
                        <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label for="description">Description</label>
                        <textarea class="form-control @error('description') is-invalid @enderror" rows="4" name="description" id="description">{{ $store->description }}</textarea>
                        @error('description')
                        <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label for="address">Address</label>
                        <textarea class="form-control @error('address') is-invalid @enderror" rows="2" name="address" id="address">{{ $store->address }}</textarea>
                        @error('address')
                        <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label for="company">Company</label>
                        <select class="form-control @error('company_id') is-invalid @enderror" name="company_id" id="company">
                            <option value="">--Select Company--</option>
                            @foreach($companies as $company)
                                <option value="{{ $company->id }}" @if ($company->id === $store->company_id) selected="selected" @endif>{{ $company->name }}</option>
                            @endforeach
                        </select>
                        @error('company_id')
                        <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>

                    <button type="submit" class="btn btn-primary">Update</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/store/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">

                <a href="{{ route('stores.create') }}" class="btn btn-primary float-right mb-3" role="button">Create Store</a>

                <table class="table">
                    <thead class="thead-light">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Name</th>
                        <th scope="col">Address</th>
                        <th scope="col">Company</th>
                        <th scope="col">Created At</th>
                        <th scope="col">Updated At</th>
                        <th scope="col" class="text-center">Operation</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($stores as $store)
                        <tr>
                            <th class="align-middle" scope="row">{{ $store->id }}</th>
                            <td class="align-middle">{{ $store->name }}</td>
                            <td class="align-middle">{{ $store->address }}</td>
                            <td class="align-middle"><a href="{{ route('companies.edit', ['id' => $store->company->id ]) }}">{{ $store->company->name }}</a></td>
                            <td class="align-middle">{{ $store->created_at }}</td>
                            <td class="align-middle">{{ $store->updated_at }}</td>
                            <td class="align-middle text-center">
                                <a href="{{ route('stores.edit', ['id' => $store->id ]) }}" class="btn btn-success" role="button">Edit</a>
                                <form action="{{route('stores.destroy',['id' => $store->id ])}}" method="POST" style="display: inline;">
                                    @method('DELETE')
                                    @csrf
                                    <button type="submit" class="btn btn-danger">Delete</button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
                {{ $stores->links() }}
            </div>
        </div>
    </div>
@endsection